<?php
 $fecha_actual = date("Ymd");
 $mes_actual=date("m");
 $ano_actual=date("Y");
 $_SESSION['FechaFiltro'] = isset($_SESSION['fechapro']) && !empty($_SESSION['fechapro']) ? $_SESSION['fechapro'] : $fecha_actual;
 $_SESSION['MesFiltro'] = isset($_SESSION['mespro']) && !empty($_SESSION['mespro']) ? $_SESSION['mespro'] : $mes_actual;
 $_SESSION['AnoFiltro'] = isset($_SESSION['anopro']) && !empty($_SESSION['anopro']) ? $_SESSION['anopro'] : $ano_actual;
 $_SESSION['CompFiltro'] = isset($_SESSION['comppro']) && !empty($_SESSION['comppro']) ? "AND T1.CODCIA = ".$_SESSION['comppro'] : "AND T1.CODCIA > "."0";
 //VALIDACIONES JS
   $ckProductos = isset($_SESSION['productosCk']) ? $_SESSION['productosCk'] : "";
   $fechafiltro = isset($_SESSION['FechaFiltro']) ? $_SESSION['FechaFiltro'] : "";
   $compfiltro = isset($_SESSION['comppro']) && !empty($_SESSION['comppro']) ? $_SESSION['comppro'] : 0;
  
   $_SESSION['filtro'] = isset($_GET['fil']) ? $_GET['fil'] : "3";
   $_SESSION['opcion'] = isset($_GET['opc']) ? $_GET['opc'] : "1";
   $tablaDIA="";$tablaMES="";
   switch ($_SESSION['filtro']) {
    case '1': //UNIDADES
      $_SESSION['logicSql'] ="SELECT COD.CODSEC CODSEC,T1.CODCIA ID,T1.CODCIA CODCIA,DES.NOMCIA COMDES, ' ' AS MON, 
      T1.CANUNI AS SUBMES, COALESCE(DIA.CANUNI, 0) AS SUBDIA
      FROM lbprddat/LO0913 AS T1 
      LEFT JOIN lbprddat/LO0912 AS DIA 
      ON DIA.CODCIA = T1.CODCIA AND DIA.FECPRO=".$_SESSION['FechaFiltro']."
      INNER JOIN LBPRDDAT/LO0686 AS COD ON COD.CODCIA = T1.CODCIA
      INNER JOIN LBPRDDAT/LO0705 AS DES ON DES.CODCIA = T1.CODCIA
      WHERE T1.ANOPRO=".$_SESSION['AnoFiltro']." AND T1.MESPRO=".$_SESSION['MesFiltro']." ".$_SESSION['CompFiltro']."
      ORDER BY COD.CODSEC";

      $comparacionAnual="SELECT T2.CODSEC CODSEC,T1.CODCIA ID, T3.NOMCIA COMDES, T1.ANO1, T1.ANO2, 
      (T1.ANO1-T1.ANO2) VARIA, ' ' AS MON FROM(SELECT ANO1.CODCIA, COALESCE(SUM(ANO1.CANUNI), 0) AS ANO1, 
      COALESCE(ANO2.CANUNI, 0) AS ANO2 
            FROM LBPRDDAT/LO0913 AS ANO1                                    
            LEFT JOIN (SELECT CODCIA, SUM(CANUNI) AS CANUNI 
           FROM LBPRDDAT/LO0913
           WHERE ANOPRO=".($_SESSION['AnoFiltro']-1)." AND MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."
           GROUP BY CODCIA) AS ANO2 
            ON ANO1.CODCIA = ANO2.CODCIA           
            WHERE ANO1.ANOPRO=".$_SESSION['AnoFiltro']." AND ANO1.MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']." 
            GROUP BY ANO1.CODCIA, ANO2.CANUNI) AS T1  
      INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = T1.CODCIA
      INNER JOIN LBPRDDAT/LO0705 AS T3 ON T3.CODCIA = T1.CODCIA
      WHERE 1=1 ".$_SESSION['CompFiltro']."       
      ORDER BY CODSEC";
       
        $promedios="SELECT CODSEC, ID,CODCIA, COMDES, MON, PRODIA, PROMES, PROANO, PROANO2, DIATRA, MESTRA, ANOTRA, ANO2TRA, SUBDIA, SUBMES, ANO1, ANO2 
        FROM(SELECT TRA.CODSEC,TRA.ID ID,TRA.ID CODCIA,TRA.COMDES COMDES,' ' AS MON, (UNIDM.SUBDIA/TRA.DIATRA) PRODIA,
      (UNIDM.SUBMES/TRA.MESTRA) PROMES, (UNIANO.ANO1/TRA.ANOTRA) PROANO,(UNIANO.ANO2/TRA.ANO2TRA) PROANO2,
      TRA.DIATRA DIATRA, TRA.MESTRA MESTRA, TRA.ANOTRA ANOTRA, TRA.ANO2TRA ANO2TRA,
      UNIDM.SUBDIA SUBDIA, UNIDM.SUBMES SUBMES, UNIANO.ANO1 ANO1, UNIANO.ANO2
      FROM(SELECT CODSEC,ID,COMDES,MON, COALESCE(TRA.NUMTRA, 0) DIATRA, MESTRA, ANOTRA, ANO2TRA 
      FROM (
          SELECT T7.CODSEC CODSEC, T1.CODCIA ID, T4.NOMCIA COMDES, T5.RELUS7 MON, MESTRA, ANOTRA, ANO2TRA                                         
          FROM (
              SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS MESTRA 
              FROM lbprddat/LO0849 AS T1 
              RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."01' AND '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."31' 
              GROUP BY T2.CODCIA
          ) AS T1 
          INNER JOIN (
              SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANOTRA                  
              FROM lbprddat/LO0849 AS T1 
              RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro']."0101' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31' 
      
              GROUP BY T2.CODCIA
          ) AS T2 ON T1.CODCIA =T2.CODCIA                                      
          INNER JOIN (
              SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANO2TRA 
              FROM lbprddat/LO0849 AS T1 
              RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".($_SESSION['AnoFiltro']-1)."0101' AND '".($_SESSION['AnoFiltro']-1).$_SESSION['MesFiltro']."31' 
              GROUP BY T2.CODCIA
          ) AS T3 ON T1.CODCIA=T3.CODCIA    
          INNER JOIN LBPRDDAT/LO0705 AS T4 ON T4.CODCIA=T1.CODCIA 
          INNER JOIN LBPRDDAT/RELAR4 AS T5 ON T5.RELCO2=T1.CODCIA 
          INNER JOIN LBPRDDAT/DETA1699 AS T6 ON T6.DETC90=T1.CODCIA 
          INNER JOIN LBPRDDAT/LO0686 AS T7 ON T7.CODCIA=T1.CODCIA
          WHERE T6.DETUSU='MARVIN' AND T6.DETPR1 = 'LO1512P' 
          ORDER BY T7.CODSEC
      ) AS TF 
      LEFT OUTER JOIN lbprddat/LO0849 AS TRA 
      ON TF.ID = TRA.CODCIA AND TRA.FECPRO=".$_SESSION['FechaFiltro'] ." ORDER BY CODSEC)AS TRA
      
      INNER JOIN 
      (SELECT COD.CODSEC CODSEC,MES.CODCIA ID,DES.NOMCIA COMDES, ' ' AS MON, 
      MES.CANUNI AS SUBMES, COALESCE(DIA.CANUNI, 0) AS SUBDIA
      FROM lbprddat/LO0913 AS MES 
      LEFT JOIN lbprddat/LO0912 AS DIA 
      ON DIA.CODCIA = MES.CODCIA AND DIA.FECPRO=".$_SESSION['FechaFiltro']."
      INNER JOIN LBPRDDAT/LO0686 AS COD ON COD.CODCIA = MES.CODCIA
      INNER JOIN LBPRDDAT/LO0705 AS DES ON DES.CODCIA = MES.CODCIA
      WHERE MES.ANOPRO=".$_SESSION['AnoFiltro']." AND MES.MESPRO=".$_SESSION['MesFiltro']."
      ORDER BY COD.CODSEC) AS UNIDM ON UNIDM.ID=TRA.ID

      INNER JOIN
       (SELECT T2.CODSEC CODSEC,T1.CODCIA ID, T3.NOMCIA COMDES, T1.ANO1, T1.ANO2, 
      (T1.ANO1-T1.ANO2) VARIA, ' ' AS MON FROM(SELECT ANO1.CODCIA, COALESCE(SUM(ANO1.CANUNI), 0) AS ANO1, 
      COALESCE(ANO2.CANUNI, 0) AS ANO2 
            FROM LBPRDDAT/LO0913 AS ANO1                                    
            LEFT JOIN (SELECT CODCIA, SUM(CANUNI) AS CANUNI 
           FROM LBPRDDAT/LO0913
           WHERE ANOPRO=".($_SESSION['AnoFiltro']-1)." AND MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."
           GROUP BY CODCIA) AS ANO2 
            ON ANO1.CODCIA = ANO2.CODCIA           
            WHERE ANO1.ANOPRO=".$_SESSION['AnoFiltro']." AND ANO1.MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."
            GROUP BY ANO1.CODCIA, ANO2.CANUNI) AS T1  
      INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = T1.CODCIA
      INNER JOIN LBPRDDAT/LO0705 AS T3 ON T3.CODCIA = T1.CODCIA      
      ORDER BY T2.CODSEC)AS UNIANO ON UNIANO.ID=TRA.ID)AS T1 WHERE 1=1 ".$_SESSION['CompFiltro']." ORDER BY CODSEC";
      $resultpromedios=odbc_exec($connIBM,$promedios); 

      break;
      case '2'://TRANSACCIONES
        
        $_SESSION['logicSql'] ="SELECT CODSEC,ID,CODCIA,COMDES,MON,SUBDIA,SUBMES FROM(SELECT CODSEC,ID, ID CODCIA, COMDES,' ' AS MON, COALESCE(TRA.NUMTRA, 0) SUBDIA, MESTRA SUBMES
        FROM (SELECT T7.CODSEC CODSEC, T1.CODCIA ID, T1.CODCIA, T4.NOMCIA COMDES, T5.RELUS7 MON, MESTRA                                       
           FROM (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS MESTRA 
                FROM lbprddat/LO0849 AS T1 
                RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."01' AND '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."31' 
                GROUP BY T2.CODCIA
            ) AS T1 
            INNER JOIN (
                SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANOTRA                  
                FROM lbprddat/LO0849 AS T1 
                RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro']."0101' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31' 
        
                GROUP BY T2.CODCIA
            ) AS T2 ON T1.CODCIA =T2.CODCIA                                      
            INNER JOIN (
                SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANO2TRA 
                FROM lbprddat/LO0849 AS T1 
                RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".($_SESSION['AnoFiltro']-1)."0101' AND '".($_SESSION['AnoFiltro']-1).$_SESSION['MesFiltro']."31' 
                GROUP BY T2.CODCIA
            ) AS T3 ON T1.CODCIA=T3.CODCIA    
            INNER JOIN LBPRDDAT/LO0705 AS T4 ON T4.CODCIA=T1.CODCIA 
            INNER JOIN LBPRDDAT/RELAR4 AS T5 ON T5.RELCO2=T1.CODCIA 
            INNER JOIN LBPRDDAT/DETA1699 AS T6 ON T6.DETC90=T1.CODCIA 
            INNER JOIN LBPRDDAT/LO0686 AS T7 ON T7.CODCIA=T1.CODCIA
            WHERE T6.DETUSU='MARVIN' AND T6.DETPR1 = 'LO1512P' 
            ORDER BY T7.CODSEC
        ) AS TF 
        LEFT OUTER JOIN lbprddat/LO0849 AS TRA 
        ON TF.ID = TRA.CODCIA AND TRA.FECPRO=".$_SESSION['FechaFiltro'] ."  ORDER BY CODSEC)AS T1 WHERE 1=1 ".$_SESSION['CompFiltro']." ORDER BY CODSEC";
      
        $comparacionAnual="SELECT CODSEC, ID, CODCIA, COMDES, MON, ANO1,ANO2,VARIA FROM(SELECT CODSEC,ID, ID CODCIA, COMDES,' ' AS MON, ANOTRA ANO1, ANO2TRA ANO2, (ANOTRA - ANO2TRA) VARIA
        FROM (SELECT T7.CODSEC CODSEC, T1.CODCIA ID, T4.NOMCIA COMDES, T5.RELUS7 MON, MESTRA, ANOTRA, ANO2TRA                                         
           FROM (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS MESTRA 
                FROM lbprddat/LO0849 AS T1 
                RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."01' AND '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."31' 
                GROUP BY T2.CODCIA
            ) AS T1 
            INNER JOIN (
                SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANOTRA                  
                FROM lbprddat/LO0849 AS T1 
                RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro']."0101' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31' 
        
                GROUP BY T2.CODCIA
            ) AS T2 ON T1.CODCIA =T2.CODCIA                                      
            INNER JOIN (
                SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANO2TRA 
                FROM lbprddat/LO0849 AS T1 
                RIGHT JOIN lbprddat/LO0705 AS T2 ON T1.CODCIA = T2.CODCIA AND T1.FECPRO BETWEEN '".($_SESSION['AnoFiltro']-1)."0101' AND '".($_SESSION['AnoFiltro']-1).$_SESSION['MesFiltro']."31' 
                GROUP BY T2.CODCIA
            ) AS T3 ON T1.CODCIA=T3.CODCIA    
            INNER JOIN LBPRDDAT/LO0705 AS T4 ON T4.CODCIA=T1.CODCIA 
            INNER JOIN LBPRDDAT/RELAR4 AS T5 ON T5.RELCO2=T1.CODCIA 
            INNER JOIN LBPRDDAT/DETA1699 AS T6 ON T6.DETC90=T1.CODCIA 
            INNER JOIN LBPRDDAT/LO0686 AS T7 ON T7.CODCIA=T1.CODCIA
            WHERE T6.DETUSU='MARVIN' AND T6.DETPR1 = 'LO1512P' 
            ORDER BY T7.CODSEC
        ) AS TF 
        LEFT OUTER JOIN lbprddat/LO0849 AS TRA 
        ON TF.ID = TRA.CODCIA AND TRA.FECPRO=".$_SESSION['FechaFiltro'] ." ORDER BY CODSEC)AS T1 WHERE 1=1 ".$_SESSION['CompFiltro']." ORDER BY CODSEC";

        $transacciones="SELECT T7.CODSEC CODSEC, T1.CODCIA ID,T4.NOMCIA COMDES,T5.RELUS7 MON,MESTRA,ANOTRA,ANO2TRA FROM(
          SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS MESTRA
          FROM lbprddat/LO0849 AS T1
          RIGHT JOIN lbprddat/LO0705 AS T2
          ON T1.CODCIA = T2.CODCIA
          AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."01' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31'
          GROUP BY T2.CODCIA) AS T1 INNER JOIN (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANOTRA
          FROM lbprddat/LO0849 AS T1
          RIGHT JOIN lbprddat/LO0705 AS T2
          ON T1.CODCIA = T2.CODCIA
          AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro']."0101' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31'
          GROUP BY T2.CODCIA) AS T2 ON T1.CODCIA =T2.CODCIA   
        INNER JOIN (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANO2TRA
          FROM lbprddat/LO0849 AS T1
          RIGHT JOIN lbprddat/LO0705 AS T2
          ON T1.CODCIA = T2.CODCIA
          AND T1.FECPRO BETWEEN '".($_SESSION['AnoFiltro']-1)."0101' AND '".($_SESSION['AnoFiltro']-1).$_SESSION['MesFiltro']."31'
          GROUP BY T2.CODCIA) AS T3 ON T1.CODCIA=T3.CODCIA   
        INNER JOIN LBPRDDAT/LO0705 AS T4 ON T4.CODCIA=T1.CODCIA 
        INNER JOIN LBPRDDAT/RELAR4 AS T5 ON T5.RELCO2=T1.CODCIA 
        INNER JOIN LBPRDDAT/DETA1699 AS T6 ON T6.DETC90=T1.CODCIA 
        INNER JOIN LBPRDDAT/LO0686 AS T7 ON T7.CODCIA=T1.CODCIA
        WHERE T6.DETUSU='MARVIN' AND T6.DETPR1 = 'LO1512P' ORDER BY T7.CODSEC";
          
        break;
        case '3':
          $tablaDIA="LO0710";
          $tablaMES="LO0711";
          break;
          case '4':
            $tablaDIA="LO0849";
            $tablaMES="LO0850";
            break;
    default:
      # code...
      break;
   }

   if ($_SESSION['filtro']==3 || $_SESSION['filtro']==4) {
    $_SESSION['logicSql'] ="SELECT T2.CODSEC,T1.CODCIA AS ID,
    T1.NOMCIA AS COMDES,T6.RELUS7 AS MON, T4.SUBTOT AS SUBDIA, 
    T5.SUBTOT AS SUBMES FROM LBPRDDAT/LO0705 AS T1 
    INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = T1.CODCIA 
    INNER JOIN LBPRDDAT/DETA1699 AS T3 ON T3.DETC90=T1.CODCIA
    INNER JOIN (SELECT CODCIA, SUM(total) AS SUBTOT
    FROM (SELECT CODCIA,VENDIA AS total FROM LBPRDDAT/LO2132
    WHERE FECFAC=".$_SESSION['FechaFiltro']." UNION ALL
    SELECT CODCIA as CODCIA,SUBTOT AS total FROM LBPRDDAT/".$tablaDIA." WHERE FECPRO=".$_SESSION['FechaFiltro']." 
    UNION ALL SELECT codcia,0 AS total FROM LBPRDDAT/".$tablaDIA."	
    WHERE NOT EXISTS ( SELECT 1 FROM LBDESDAT/".$tablaDIA." WHERE fecpro = ".$_SESSION['FechaFiltro'].")) AS Total  
    GROUP BY CODCIA ) AS T4 ON T4.CODCIA = T1.CODCIA
    INNER JOIN ( SELECT CODCIA, SUM(SUBTOT) SUBTOT FROM(
    SELECT codcia, subtot FROM LBPRDDAT/".$tablaMES." 
    WHERE MESPRO = ".$_SESSION['MesFiltro']." AND ANOPRO =".$_SESSION['AnoFiltro']." UNION ALL SELECT codcia, 0 AS subtot FROM LBPRDDAT/".$tablaMES." 
    WHERE NOT EXISTS (SELECT 1 FROM LBDESDAT/".$tablaMES." WHERE MESPRO= ".$_SESSION['MesFiltro']." AND ANOPRO=".$_SESSION['AnoFiltro']." )GROUP BY CODCIA)GROUP BY CODCIA ORDER BY CODCIA) AS T5 
    ON T5.CODCIA = T1.CODCIA INNER JOIN LBPRDDAT/RELAR4 AS T6 ON 
    T6.RELCO2 = T1.CODCIA WHERE T3.DETUSU='MARVIN' AND T3.DETPR1 = 'LO1512P' ".$_SESSION['CompFiltro']." ORDER BY T2.CODSEC";
  
    $comparacionAnual="SELECT CODSEC, ID,CODCIA, COMDES, MON, ANO1, ANO2, VARIA FROM (
      SELECT T1.CODSEC CODSEC,T1.CODCIA ID,T1.CODCIA CODCIA, T3.NOMCIA COMDES,T4.RELUS7 MON,T1.ANO1 ANO1,T2.ANO2 ANO2, 
    (T1.ANO1 - T2.ANO2) VARIA
    FROM (SELECT T3.CODSEC,T2.CODCIA, COALESCE(SUM(T1.SUBTOT), 0) AS ANO1
    FROM lbprddat/".$tablaMES." AS T1                                   
    LEFT JOIN LBPRDDAT/LO0686 AS T3 ON T1.CODCIA = T3.CODCIA     
    RIGHT JOIN LBPRDDAT/LO0705 AS T2                             
    ON T1.CODCIA = T2.CODCIA                                     
    AND T1.ANOPRO = ".$_SESSION['AnoFiltro']."                                         
    AND T1.MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."                                
    GROUP BY T2.CODCIA,T3.CODSEC) AS T1
    INNER JOIN (SELECT T3.CODSEC,T2.CODCIA, COALESCE(SUM(T1.SUBTOT), 0) AS ANO2
    FROM lbprddat/".$tablaMES." AS T1                                   
    LEFT JOIN LBPRDDAT/LO0686 AS T3 ON T1.CODCIA = T3.CODCIA     
    RIGHT JOIN LBPRDDAT/LO0705 AS T2                             
    ON T1.CODCIA = T2.CODCIA                                     
    AND T1.ANOPRO = ".($_SESSION['AnoFiltro']-1)."                                          
    AND T1.MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."                                  
    GROUP BY T2.CODCIA,T3.CODSEC) AS T2
    ON T2.CODCIA=T1.CODCIA INNER JOIN LBPRDDAT/LO0705 AS T3 
    ON T3.CODCIA=T1.CODCIA INNER JOIN LBPRDDAT/RELAR4 AS T4 
    ON T4.RELCO2=T1.CODCIA INNER JOIN LBPRDDAT/DETA1699 AS T5
    ON T5.DETC90=T1.CODCIA 
    WHERE T5.DETUSU='MARVIN' AND T5.DETPR1 = 'LO1512P' ORDER BY T1.CODSEC) AS T1 WHERE 1=1 ".$_SESSION['CompFiltro']." ORDER BY CODSEC";

      $promedios="SELECT CODSEC,ID,COMDES,MON,(SUBDIA/DIATRA)PRODIA,(SUBMES/MESTRA)PROMES,(ANO1/ANOTRA)PROANO,(ANO2/ANO2TRA)PROANO2 FROM(SELECT T1.CODSEC,T1.ID,T1.COMDES,T1.MON, T1.SUBDIA,T1.SUBMES,T2.ANO1,T2.ANO2,T2.VARIA,T1.DIATRA,T3.MESTRA,T3.ANOTRA,T3.ANO2TRA FROM (SELECT T2.CODSEC,T1.CODCIA AS ID,
      T1.NOMCIA AS COMDES,T6.RELUS7 AS MON, T4.SUBTOT AS SUBDIA,T4.NUMTRA AS DIATRA, 
      T5.SUBTOT AS SUBMES FROM LBPRDDAT/LO0705 AS T1 
      INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = T1.CODCIA 
      INNER JOIN LBPRDDAT/DETA1699 AS T3 ON T3.DETC90=T1.CODCIA
      INNER JOIN (SELECT Total.CODCIA, Total.SUBTOT, COALESCE(TRA.NUMTRA, 0) AS NUMTRA 
    FROM (SELECT CODCIA, SUM(total) AS SUBTOT 
            FROM (SELECT CODCIA, VENDIA AS total, 1 NUMTRA 
            FROM LBPRDDAT/LO2132 WHERE FECFAC = ".$_SESSION['FechaFiltro']." 
            UNION ALL SELECT CODCIA AS CODCIA, SUBTOT AS total, NUMTRA 
            FROM LBPRDDAT/".$tablaDIA." WHERE FECPRO = ".$_SESSION['FechaFiltro']." UNION ALL 
            SELECT codcia, 0 AS total, NUMTRA FROM LBPRDDAT/".$tablaDIA." 
            WHERE NOT EXISTS (SELECT 1 FROM LBDESDAT/".$tablaDIA." WHERE fecpro=".$_SESSION['FechaFiltro']."
            ))GROUP BY CODCIA) AS Total LEFT JOIN LBPRDDAT/".$tablaDIA." AS TRA 
    ON TRA.CODCIA = Total.CODCIA AND TRA.FECPRO = ".$_SESSION['FechaFiltro'].") AS T4 ON T4.CODCIA = T1.CODCIA
      INNER JOIN ( SELECT CODCIA, SUM(SUBTOT) SUBTOT FROM(
        SELECT codcia, subtot FROM LBPRDDAT/".$tablaMES." 
        WHERE MESPRO = ".$_SESSION['MesFiltro']." AND ANOPRO =".$_SESSION['AnoFiltro']." UNION ALL SELECT codcia, 0 AS subtot FROM LBPRDDAT/".$tablaMES." 
        WHERE NOT EXISTS (SELECT 1 FROM LBDESDAT/".$tablaMES." WHERE MESPRO= ".$_SESSION['MesFiltro']." AND ANOPRO=".$_SESSION['AnoFiltro']." )GROUP BY CODCIA)GROUP BY CODCIA ORDER BY CODCIA) AS T5 
      ON T5.CODCIA = T1.CODCIA INNER JOIN LBPRDDAT/RELAR4 AS T6 ON 
      T6.RELCO2 = T1.CODCIA WHERE T3.DETUSU='MARVIN' AND T3.DETPR1 = 'LO1512P' ".$_SESSION['CompFiltro']." ORDER BY T2.CODSEC) AS T1
      INNER JOIN (
      SELECT T1.CODSEC CODSEC,T1.CODCIA ID,T3.NOMCIA COMDES,T4.RELUS7 MON,T1.ANO1 ANO1,T2.ANO2 ANO2, 
      (T1.ANO1 - T2.ANO2) VARIA
      FROM (SELECT T3.CODSEC,T2.CODCIA, COALESCE(SUM(T1.SUBTOT), 0) AS ANO1
      FROM lbprddat/".$tablaMES." AS T1                                   
      LEFT JOIN LBPRDDAT/LO0686 AS T3 ON T1.CODCIA = T3.CODCIA     
      RIGHT JOIN LBPRDDAT/LO0705 AS T2                             
      ON T1.CODCIA = T2.CODCIA                                     
      AND T1.ANOPRO = ".$_SESSION['AnoFiltro']."                                         
      AND T1.MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."                                
      GROUP BY T2.CODCIA,T3.CODSEC) AS T1
      INNER JOIN (SELECT T3.CODSEC,T2.CODCIA, COALESCE(SUM(T1.SUBTOT), 0) AS ANO2
      FROM lbprddat/".$tablaMES." AS T1                                   
      LEFT JOIN LBPRDDAT/LO0686 AS T3 ON T1.CODCIA = T3.CODCIA     
      RIGHT JOIN LBPRDDAT/LO0705 AS T2                             
      ON T1.CODCIA = T2.CODCIA                                     
      AND T1.ANOPRO = ".($_SESSION['AnoFiltro']-1)."                                          
      AND T1.MESPRO BETWEEN 1 AND ".$_SESSION['MesFiltro']."                                  
      GROUP BY T2.CODCIA,T3.CODSEC) AS T2
      ON T2.CODCIA=T1.CODCIA INNER JOIN LBPRDDAT/LO0705 AS T3 
      ON T3.CODCIA=T1.CODCIA INNER JOIN LBPRDDAT/RELAR4 AS T4 
      ON T4.RELCO2=T1.CODCIA INNER JOIN LBPRDDAT/DETA1699 AS T5
      ON T5.DETC90=T1.CODCIA 
      WHERE T5.DETUSU='MARVIN' AND T5.DETPR1 = 'LO1512P' ORDER BY T2.CODSEC) AS T2 ON T1.ID=T2.ID
      INNER JOIN (
        SELECT T7.CODSEC CODSEC, T1.CODCIA ID,T4.NOMCIA COMDES,T5.RELUS7 MON,MESTRA,ANOTRA,ANO2TRA FROM(
          SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS MESTRA
          FROM lbprddat/".$tablaDIA." AS T1
          RIGHT JOIN lbprddat/LO0705 AS T2
          ON T1.CODCIA = T2.CODCIA
          AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro'].$_SESSION['MesFiltro']."01' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31'
          GROUP BY T2.CODCIA) AS T1 INNER JOIN (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANOTRA
          FROM lbprddat/".$tablaDIA." AS T1
          RIGHT JOIN lbprddat/LO0705 AS T2
          ON T1.CODCIA = T2.CODCIA
          AND T1.FECPRO BETWEEN '".$_SESSION['AnoFiltro']."0101' AND '".($_SESSION['AnoFiltro']).$_SESSION['MesFiltro']."31'
          GROUP BY T2.CODCIA) AS T2 ON T1.CODCIA =T2.CODCIA   
        INNER JOIN (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANO2TRA
          FROM lbprddat/".$tablaDIA." AS T1
          RIGHT JOIN lbprddat/LO0705 AS T2
          ON T1.CODCIA = T2.CODCIA
          AND T1.FECPRO BETWEEN '".($_SESSION['AnoFiltro']-1)."0101' AND '".($_SESSION['AnoFiltro']-1).$_SESSION['MesFiltro']."31'
          GROUP BY T2.CODCIA) AS T3 ON T1.CODCIA=T3.CODCIA   
        INNER JOIN LBPRDDAT/LO0705 AS T4 ON T4.CODCIA=T1.CODCIA 
        INNER JOIN LBPRDDAT/RELAR4 AS T5 ON T5.RELCO2=T1.CODCIA 
        INNER JOIN LBPRDDAT/DETA1699 AS T6 ON T6.DETC90=T1.CODCIA 
        INNER JOIN LBPRDDAT/LO0686 AS T7 ON T7.CODCIA=T1.CODCIA
        WHERE T6.DETUSU='MARVIN' AND T6.DETPR1 = 'LO1512P' ORDER BY T7.CODSEC) AS T3 ON T3.ID = T1.ID) ORDER BY CODSEC";
        $resultpromedios=odbc_exec($connIBM,$promedios); 
   }

 
  
  $sqlquery_zlo0001p = isset($_SESSION['logicSql']) ? $_SESSION['logicSql'] : " ";                    
  $result_zlo0001p=odbc_exec($connIBM,$sqlquery_zlo0001p);
 
  $result_compAnual=odbc_exec($connIBM,$comparacionAnual);


   //COMBOBOX
   $sqlCOMARC = "SELECT T2.CODSEC,LO0705.CODCIA COMCOD, LO0705.NOMCIA COMDES 
   FROM LBPRDDAT/LO0705
   INNER JOIN LBPRDDAT/DETA16 ON DETA16.DETC90 = LO0705.CODCIA
   INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = LO0705.CODCIA
   WHERE DETA16.DETUSU ='".$_SESSION["CODUSU"]."' AND DETA16.DETPR1 = 'LO1512P'
   ORDER BY T2.CODSEC";
   $resultCOMARC=odbc_exec($connIBM,$sqlCOMARC);

?>
 