<?php
 $fecha_actual = date("Ymd");
 $mes_actual=date("m");
 $ano_actual=date("Y");
 $_SESSION['FechaFiltro'] = isset($_SESSION['fechapro']) && !empty($_SESSION['fechapro']) ? $_SESSION['fechapro'] : $fecha_actual;
 $_SESSION['MesFiltro'] = isset($_SESSION['mespro']) && !empty($_SESSION['mespro']) ? $_SESSION['mespro'] : $mes_actual;
 $_SESSION['AnoFiltro'] = isset($_SESSION['anopro']) && !empty($_SESSION['anopro']) ? $_SESSION['anopro'] : $ano_actual;
 $_SESSION['CompFiltro'] = isset($_SESSION['comppro']) && !empty($_SESSION['comppro']) ? "AND T1.CODCIA = ".$_SESSION['comppro'] : "AND T1.CODCIA > "."0";
 //VALIDACIONES JS
   $ckProductos = isset($_SESSION['productosCk']) ? $_SESSION['productosCk'] : "";
   $fechafiltro = isset($_SESSION['FechaFiltro']) ? $_SESSION['FechaFiltro'] : "";
   $compfiltro = isset($_SESSION['comppro']) && !empty($_SESSION['comppro']) ? $_SESSION['comppro'] : 0;
 
     $_SESSION['logicSql'] ="SELECT T2.CODSEC,T1.CODCIA AS ID,
   T1.NOMCIA AS COMDES,T6.RELUS7 AS MON, T4.SUBTOT AS SUBDIA, 
   T5.SUBTOT AS SUBMES FROM LBPRDDAT/LO0705 AS T1 
   INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = T1.CODCIA 
   INNER JOIN LBPRDDAT/DETA1699 AS T3 ON T3.DETC90=T1.CODCIA
   INNER JOIN (SELECT CODCIA, SUM(total) AS SUBTOT
   FROM (SELECT CODCIA,VENDIA AS total FROM LBPRDDAT/LO2132
   WHERE FECFAC=".$_SESSION['FechaFiltro']." UNION ALL
   SELECT CODCIA as CODCIA,SUBTOT AS total FROM LBPRDDAT/LO0849 WHERE FECPRO=".$_SESSION['FechaFiltro']." 
   UNION ALL SELECT codcia,0 AS total FROM LBPRDDAT/LO0849	
   WHERE NOT EXISTS ( SELECT 1 FROM LBDESDAT/LO0849 WHERE fecpro = ".$_SESSION['FechaFiltro'].")) AS Total  
   GROUP BY CODCIA ) AS T4 ON T4.CODCIA = T1.CODCIA
   INNER JOIN ( SELECT CODCIA, SUM(SUBTOT) SUBTOT FROM(
    SELECT codcia, subtot FROM LBPRDDAT/LO0850 
    WHERE MESPRO = ".$_SESSION['MesFiltro']." AND ANOPRO =".$_SESSION['AnoFiltro']." UNION ALL SELECT codcia, 0 AS subtot FROM LBPRDDAT/LO0850 
    WHERE NOT EXISTS (SELECT 1 FROM LBDESDAT/LO0850 WHERE MESPRO= ".$_SESSION['MesFiltro']." AND ANOPRO=".$_SESSION['AnoFiltro']." )GROUP BY CODCIA)GROUP BY CODCIA ORDER BY CODCIA) AS T5 
   ON T5.CODCIA = T1.CODCIA INNER JOIN LBPRDDAT/RELAR4 AS T6 ON 
   T6.RELCO2 = T1.CODCIA WHERE T3.DETUSU='MARVIN' AND T3.DETPR1 = 'LO1512P' ".$_SESSION['CompFiltro']." ORDER BY T2.CODSEC";
   $sqlquery_zlo0001p = isset($_SESSION['logicSql']) ? $_SESSION['logicSql'] : " ";                    
   $result_zlo0001p=odbc_exec($connIBM,$sqlquery_zlo0001p);

  $comparacionAnual="SELECT T1.CODSEC CODSEC,T1.CODCIA ID,T3.NOMCIA COMDES,T4.RELUS7 MON,T1.ANO1 ANO1,T2.ANO2 ANO2, 
  (T1.ANO1 - T2.ANO2) VARIA
  FROM (SELECT T3.CODSEC,T2.CODCIA, COALESCE(SUM(T1.SUBTOT), 0) AS ANO1
  FROM lbprddat/LO0850 AS T1                                   
  LEFT JOIN LBPRDDAT/LO0686 AS T3 ON T1.CODCIA = T3.CODCIA     
  RIGHT JOIN LBPRDDAT/LO0705 AS T2                             
  ON T1.CODCIA = T2.CODCIA                                     
  AND T1.ANOPRO = 2023                                         
  AND T1.MESPRO BETWEEN 1 AND 4                                
  GROUP BY T2.CODCIA,T3.CODSEC) AS T1
INNER JOIN (SELECT T3.CODSEC,T2.CODCIA, COALESCE(SUM(T1.SUBTOT), 0) AS ANO2
  FROM lbprddat/LO0850 AS T1                                   
  LEFT JOIN LBPRDDAT/LO0686 AS T3 ON T1.CODCIA = T3.CODCIA     
  RIGHT JOIN LBPRDDAT/LO0705 AS T2                             
  ON T1.CODCIA = T2.CODCIA                                     
  AND T1.ANOPRO = 2022                                         
  AND T1.MESPRO BETWEEN 1 AND 4                                
  GROUP BY T2.CODCIA,T3.CODSEC) AS T2
ON T2.CODCIA=T1.CODCIA INNER JOIN LBPRDDAT/LO0705 AS T3 
ON T3.CODCIA=T1.CODCIA INNER JOIN LBPRDDAT/RELAR4 AS T4 
ON T4.RELCO2=T1.CODCIA INNER JOIN LBPRDDAT/DETA1699 AS T5
ON T5.DETC90=T1.CODCIA 
WHERE T5.DETUSU='MARVIN' AND T5.DETPR1 = 'LO1512P' ORDER BY T2.CODSEC";
$result_compAnual=odbc_exec($connIBM,$comparacionAnual);



$transacciones="SELECT T7.CODSEC CODSEC, T1.CODCIA ID,T4.NOMCIA COMDES,T5.RELUS7 MON,MESTRA,ANOTRA,ANO2TRA FROM(
    SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS MESTRA
    FROM lbprddat/LO0849 AS T1
    RIGHT JOIN lbprddat/LO0705 AS T2
    ON T1.CODCIA = T2.CODCIA
    AND T1.FECPRO BETWEEN '20230401' AND '20230431'
    GROUP BY T2.CODCIA) AS T1 INNER JOIN (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANOTRA
    FROM lbprddat/LO0849 AS T1
    RIGHT JOIN lbprddat/LO0705 AS T2
    ON T1.CODCIA = T2.CODCIA
    AND T1.FECPRO BETWEEN '20230101' AND '20230431'
    GROUP BY T2.CODCIA) AS T2 ON T1.CODCIA =T2.CODCIA   
  INNER JOIN (SELECT T2.CODCIA, COALESCE(SUM(T1.NUMTRA), 0) AS ANO2TRA
    FROM lbprddat/LO0849 AS T1
    RIGHT JOIN lbprddat/LO0705 AS T2
    ON T1.CODCIA = T2.CODCIA
    AND T1.FECPRO BETWEEN '20220101' AND '20220431'
    GROUP BY T2.CODCIA) AS T3 ON T1.CODCIA=T3.CODCIA   
  INNER JOIN LBPRDDAT/LO0705 AS T4 ON T4.CODCIA=T1.CODCIA 
  INNER JOIN LBPRDDAT/RELAR4 AS T5 ON T5.RELCO2=T1.CODCIA 
  INNER JOIN LBPRDDAT/DETA1699 AS T6 ON T6.DETC90=T1.CODCIA 
  INNER JOIN LBPRDDAT/LO0686 AS T7 ON T7.CODCIA=T1.CODCIA
  WHERE T6.DETUSU='MARVIN' AND T6.DETPR1 = 'LO1512P' ORDER BY T7.CODSEC";

$result_transacciones=odbc_exec($connIBM,$transacciones);
 
   
   $sqlCOMARC = "SELECT T2.CODSEC,COMARC.COMCOD, COMARC.COMDES 
   FROM LBPRDDAT/COMARC
   INNER JOIN LBPRDDAT/DETA16 ON DETA16.DETC90 = COMARC.COMCOD
   INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = COMARC.COMCOD
   WHERE DETA16.DETUSU ='".$_SESSION["CODUSU"]."' AND DETA16.DETPR1 = 'LO1512P' 
   ORDER BY T2.CODSEC";
   $resultCOMARC=odbc_exec($connIBM,$sqlCOMARC);

?>
 