<?php
function obtenerNombreMes($numeroMes) {
    $nombresMes = array('ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE');
    return $nombresMes[$numeroMes - 1];
  }
  function obtenerNombreMesAbr($numeroMes) {
    $nombresMes = array('Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic');
    return $nombresMes[$numeroMes - 1];
  }
  function obtenerNumeroMes($nombre_mes) {
    $nombres_mes = array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
    $numero_mes = array_search($nombre_mes, $nombres_mes) + 1;
    return $numero_mes;
  }

   $mes_actual=date("m");
   $ano_actual=date("Y");
   $mesLabel1 = (isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes1'])):  obtenerNombreMesAbr(1);
   $mesLabel2 = (isset($_SESSION['mes2']) && $_SESSION['mes2']!=' ')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes2'])):  obtenerNombreMesAbr($mes_actual);
   $mesNum1=(isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNumeroMes($_SESSION['mes1']):  '01';
   $mesNum2=(isset($_SESSION['mes2']) && $_SESSION['mes2']!='')? obtenerNumeroMes($_SESSION['mes2']):  $mes_actual;

   $ano1 = (isset($_SESSION['ano1']) && $_SESSION['ano1']!='')? $_SESSION['ano1']:  $ano_actual;
   $ano2 = (isset($_SESSION['ano2']) && $_SESSION['ano2']!='')? $_SESSION['ano2']:  $ano_actual;
   $labelSelect= "$mesLabel1 $ano1 - $mesLabel2 $ano2";

        $mesfiltro=$mesNum2;
        $anofiltro=isset($_SESSION['anofiltro'])? $_SESSION['anofiltro']: $ano_actual;
        $marcaFiltro=isset($_SESSION['marcaFiltro'])? $_SESSION['marcaFiltro']: 100;
        if (strlen($mesfiltro)==1) {
          $mesfiltro="0".$mesfiltro;
        }
//DESCRIPCIONES
$marcasDescripcion="SELECT * FROM LBPRDDAT/DESARC WHERE DESCOD=01";
$resultDescripcion=odbc_exec($connIBM,$marcasDescripcion);
$_SESSION['mesFiltro']=$_SESSION['mesFiltro']-1;
$valorFiltro=$anofiltro.(strlen($_SESSION['mesFiltro'])==1? "0".$_SESSION['mesFiltro']:$_SESSION['mesFiltro']);
//HONDURAS
 $marcassql="SELECT HON.MARCA MARCA,HON.DESDES DESDES,HON.CANANO1 CANHON,HON.VALANO1 VALHON,HON.CANANO2 CANHON2,HON.VALANO2 VALHON2,
GUA.CANANO1 CANGUA,GUA.VALANO1 VALGUA,GUA.CANANO2 CANGUA2,GUA.VALANO2 VALGUA2,
 SAL.CANANO1 CANSAL,SAL.VALANO1 VALSAL,SAL.CANANO2 CANSAL2,SAL.VALANO2 VALSAL2,
 COS.CANANO1 CANCOS,COS.VALANO1 VALCOS,COS.CANANO2 CANCOS2,COS.VALANO2 VALCOS2,
 REP.CANANO1 CANREP,REP.VALANO1 VALREP,REP.CANANO2 CANREP2,REP.VALANO2 VALREP2,
 NIC.CANANO1 CANNIC,NIC.VALANO1 VALNIC,NIC.CANANO2 CANNIC2,NIC.VALANO2 VALNIC2
FROM(
SELECT ANO1.MARCA,ANO1.DESDES,ANO1.CANVEN AS CANANO1, ANO1.VALVEN AS VALANO1, ANO2.CANVEN AS CANANO2, ANO2.VALVEN AS VALANO2 FROM (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=11 AND T2.ANOPRO=".($ano2)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO1 INNER JOIN (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=11 AND T2.ANOPRO=".($ano2-1)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO2 ON ANO1.MARCA = ANO2.MARCA AND ANO1.DESDES = ANO2.DESDES
) AS HON
INNER JOIN (
SELECT ANO1.MARCA,ANO1.DESDES,ANO1.CANVEN AS CANANO1, ANO1.VALVEN AS VALANO1, ANO2.CANVEN AS CANANO2, ANO2.VALVEN AS VALANO2 FROM (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=10 AND T2.ANOPRO=".($ano2)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO1 INNER JOIN (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=10 AND T2.ANOPRO=".($ano2-1)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO2 ON ANO1.MARCA = ANO2.MARCA AND ANO1.DESDES = ANO2.DESDES
) AS GUA ON HON.MARCA = GUA.MARCA
INNER JOIN (
SELECT ANO1.MARCA,ANO1.DESDES,ANO1.CANVEN AS CANANO1, ANO1.VALVEN AS VALANO1, ANO2.CANVEN AS CANANO2, ANO2.VALVEN AS VALANO2 FROM (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=12 AND T2.ANOPRO=".($ano2)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO1 INNER JOIN (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=12 AND T2.ANOPRO=".($ano2-1)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO2 ON ANO1.MARCA = ANO2.MARCA AND ANO1.DESDES = ANO2.DESDES
) AS SAL ON HON.MARCA = SAL.MARCA
INNER JOIN (
SELECT ANO1.MARCA,ANO1.DESDES,ANO1.CANVEN AS CANANO1, ANO1.VALVEN AS VALANO1, ANO2.CANVEN AS CANANO2, ANO2.VALVEN AS VALANO2 FROM (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=13 AND T2.ANOPRO=".($ano2)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO1 INNER JOIN (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=13 AND T2.ANOPRO=".($ano2-1)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO2 ON ANO1.MARCA = ANO2.MARCA AND ANO1.DESDES = ANO2.DESDES
) AS COS ON HON.MARCA = COS.MARCA
INNER JOIN (
SELECT ANO1.MARCA,ANO1.DESDES,ANO1.CANVEN AS CANANO1, ANO1.VALVEN AS VALANO1, ANO2.CANVEN AS CANANO2, ANO2.VALVEN AS VALANO2 FROM (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=15 AND T2.ANOPRO=".($ano2)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO1 INNER JOIN (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=15 AND T2.ANOPRO=".($ano2-1)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO2 ON ANO1.MARCA = ANO2.MARCA AND ANO1.DESDES = ANO2.DESDES
) AS REP ON HON.MARCA = REP.MARCA
INNER JOIN (
SELECT ANO1.MARCA,ANO1.DESDES,ANO1.CANVEN AS CANANO1, ANO1.VALVEN AS VALANO1, ANO2.CANVEN AS CANANO2, ANO2.VALVEN AS VALANO2 FROM (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=16 AND T2.ANOPRO=".($ano2)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO1 INNER JOIN (SELECT DESCO1 AS MARCA,DESDES, SUM(CANVEN) AS CANVEN, SUM(VALVEN) AS VALVEN FROM (SELECT DESCO1,DESDES, COALESCE(FLOOR(((FLOOR(CANVEN)*12) +ROUND((CANVEN - FLOOR(CANVEN)) * 100))),0) AS CANVEN, COALESCE(VALVEN,0) AS VALVEN FROM LBPRDDAT/DESARC AS DESTABLA LEFT JOIN (SELECT T2.CODCIA, T2.ANOPRO, T2.MESPRO, T2.MARCA, T2.CANVEN,T2.VALVEN FROM LBPRDDAT/LO0703 AS T1 INNER JOIN LBPRDDAT/LO2234 AS T2 ON T1.CODCIA=T2.CODCIA WHERE T1.CODIGO=16 AND T2.ANOPRO=".($ano2-1)." AND T2.MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." ORDER BY T2.MESPRO ) AS VENTABLA ON DESTABLA.DESCO1=VENTABLA.MARCA WHERE DESCOD=1 AND DESCO1<=950) AS T GROUP BY DESCO1,DESDES ORDER BY DESCO1) AS ANO2 ON ANO1.MARCA = ANO2.MARCA AND ANO1.DESDES = ANO2.DESDES
) AS NIC ON HON.MARCA = NIC.MARCA";

    $resultMarcas=odbc_exec($connIBM,$marcassql);



?>