<?php
function obtenerNombreMes($numeroMes) {
  $nombresMes = array('ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE');
  return $nombresMes[$numeroMes - 1];
}
function obtenerNombreMesAbr($numeroMes) {
  $nombresMes = array('Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic');
  return $nombresMes[$numeroMes - 1];
}
function obtenerNumeroMes($nombre_mes) {
  $nombres_mes = array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
  $numero_mes = array_search($nombre_mes, $nombres_mes) + 1;
  return $numero_mes;
}

 $mes_actual=date("m");
 $ano_actual=date("Y");
 $mesLabel1 = (isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes1'])):  obtenerNombreMesAbr(1);
 $mesLabel2 = (isset($_SESSION['mes2']) && $_SESSION['mes2']!=' ')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes2'])):  obtenerNombreMesAbr($mes_actual);
 $mesNum1=(isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNumeroMes($_SESSION['mes1']):  '01';
 $mesNum2=(isset($_SESSION['mes2']) && $_SESSION['mes2']!='')? obtenerNumeroMes($_SESSION['mes2']):  $mes_actual;

 $ano1 = (isset($_SESSION['ano1']) && $_SESSION['ano1']!='')? $_SESSION['ano1']:  $ano_actual;
 $ano2 = (isset($_SESSION['ano2']) && $_SESSION['ano2']!='')? $_SESSION['ano2']:  $ano_actual;
 $labelSelect= "$mesLabel1 $ano1 - $mesLabel2 $ano2";
 //echo $mesNum1.' '.$ano1.' - '.$mesNum2.' '.$ano2;

      $mesfiltro=isset($_SESSION['mesFiltro'])? $_SESSION['mesFiltro']:  $mes_actual; 
      $anofiltro=isset($_SESSION['anofiltro'])? $_SESSION['anofiltro']: $ano_actual; 
      isset($_SESSION['validacion'])? $_SESSION['validacion']:$_SESSION['validacion']="false";
      
      if (!isset($_SESSION['mesFiltro'])) {
          $_SESSION['mesFiltro']=$mesfiltro;
      }else{
          if($_SESSION['validacion']=="true"){
              $_SESSION['mesFiltro']=$mesfiltro;
              $_SESSION['validacion']="false";
          }
      }
   
    $marcaFiltro=isset($_SESSION['marcaFiltro'])? $_SESSION['marcaFiltro']: 100; 
    //DESCRIPCIONES
    $marcasDescripcion="SELECT * FROM LBPRDDAT/DESARC WHERE DESCOD=01";
    $resultDescripcion=odbc_exec($connIBM,$marcasDescripcion);

    //FACTORES CAMBIO

  
  $valorFiltro=$anofiltro.$_SESSION['mesFiltro'];
  
  //FACTORES CAMBIO
   $sqlfactor="SELECT  * FROM (
      (SELECT * FROM lbprddat/lo0709 WHERE MONORI='L' AND MONDES='D' AND FECPRO LIKE '".trim($valorFiltro)."%'
        ORDER BY FECPRO DESC LIMIT 1)
      UNION ALL   
      (SELECT * FROM lbprddat/lo0709 WHERE MONORI='Q' AND MONDES='D' AND FECPRO LIKE '".trim($valorFiltro)."%'
        ORDER BY FECPRO DESC LIMIT 1)       
      UNION ALL 
      (SELECT * FROM lbprddat/lo0709 WHERE MONORI='C' AND MONDES='D' AND FECPRO LIKE '".trim($valorFiltro)."%'
        ORDER BY FECPRO DESC LIMIT 1)
      UNION ALL          
      (SELECT * FROM lbprddat/lo0709 WHERE MONORI='P' AND MONDES='D' AND FECPRO LIKE '".trim($valorFiltro)."%'
        ORDER BY FECPRO DESC LIMIT 1)        
      UNION ALL 
      (SELECT * FROM lbprddat/lo0709 WHERE MONORI='D' AND MONDES='D' AND FECPRO LIKE '".trim($valorFiltro)."%'
        ORDER BY FECPRO DESC LIMIT 1))";
      
  $factorL=0;$factorQ=0;$factorC=0;$factorP=0;$factorD=1;
   $resultFactor=odbc_exec($connIBM,$sqlfactor); 
  if (!odbc_num_rows($resultFactor)) {
      $_SESSION['mesFiltro']=($_SESSION['mesFiltro']-1);
      if (strlen($_SESSION['mesFiltro'])==1) {
          $_SESSION['mesFiltro']='0'.($_SESSION['mesFiltro']);
      }
      $_SESSION['validacion']=="false";
      echo '<script>window.location.replace("/'.$_SESSION['DEV'].'LovablePHP/PRG/ZFA/ZLO0003P.php")</script>'; 
  }
   
   while($rowFactor = odbc_fetch_array($resultFactor)){
      switch ($rowFactor['MONORI']) {
          case 'L':
              $factorL=$rowFactor['FACTOR'];
              break;
              case 'Q':
                  $factorQ=$rowFactor['FACTOR'];
                  break;
                  case 'C':
                      $factorC=$rowFactor['FACTOR'];
                      break;
                      case 'P':
                          $factorP=$rowFactor['FACTOR'];
                          break;
          default:
                  $factorD=1;
              break;
      }
  }    
  

    //VALORES

    $marcassql="SELECT HON.HISM38 HISM38,HON.DESDES DESDES,HON.CANANO1 HONCANANO1,HON.VALANO1 HONVALANO1,HON.CANANO2 HONCANANO2,HON.VALANO2 HONVALANO2, 
                                                           GUA.CANANO1 GUACANANO1,GUA.VALANO1 GUAVALANO1,GUA.CANANO2 GUACANANO2,GUA.VALANO2 GUAVALANO2,
                                                           SAL.CANANO1 SALCANANO1,SAL.VALANO1 SALVALANO1,SAL.CANANO2 SALCANANO2,SAL.VALANO2 SALVALANO2,
                                                           COS.CANANO1 COSCANANO1,COS.VALANO1 COSVALANO1,COS.CANANO2 COSCANANO2,COS.VALANO2 COSVALANO2,
                                                           REP.CANANO1 REPCANANO1,REP.VALANO1 REPVALANO1,REP.CANANO2 REPCANANO2,REP.VALANO2 REPVALANO2,
                                                           NIC.CANANO1 NICCANANO1,NIC.VALANO1 NICVALANO1,NIC.CANANO2 NICCANANO2,NIC.VALANO2 NICVALANO2
    FROM(
    SELECT ANO1.HISM38 HISM38,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
    FROM (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (35,47,50,52,56,57,59,63,64,65,68,70,72,73,74,75,76,78,82,85)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO1 INNER JOIN (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro-1)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (35,47,50,52,56,57,59,63,64,65,68,70,72,73,74,75,76,78,82,85)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO2 ON ANO1.HISM38=ANO2.HISM38 WHERE ANO1.HISM38= ".$marcaFiltro.") HON INNER JOIN
    (SELECT ANO1.HISM38 HISM38,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
    FROM (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (49,66,69,71,86)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO1 INNER JOIN (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro-1)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (49,66,69,71,86)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO2 ON ANO1.HISM38=ANO2.HISM38 WHERE ANO1.HISM38=".$marcaFiltro.") GUA ON HON.HISM38=GUA.HISM38 LEFT JOIN
    (SELECT ANO1.HISM38 HISM38,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
    FROM (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (48,53,61,62,77)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO1 INNER JOIN (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro-1)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (48,53,61,62,77)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO2 ON ANO1.HISM38=ANO2.HISM38 WHERE ANO1.HISM38=".$marcaFiltro.") SAL ON HON.HISM38=SAL.HISM38 LEFT JOIN
    (SELECT ANO1.HISM38 HISM38,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
    FROM (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (54,60,80)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO1 INNER JOIN (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro-1)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (54,60,80)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO2 ON ANO1.HISM38=ANO2.HISM38 WHERE ANO1.HISM38=".$marcaFiltro.") COS ON HON.HISM38=COS.HISM38 LEFT JOIN
    (SELECT ANO1.HISM38 HISM38,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
    FROM (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (81)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO1 INNER JOIN (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro-1)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (81)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO2 ON ANO1.HISM38=ANO2.HISM38 WHERE ANO1.HISM38=".$marcaFiltro.") REP ON HON.HISM38=REP.HISM38 LEFT JOIN
    (SELECT ANO1.HISM38 HISM38,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
    FROM (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (83,87)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO1 INNER JOIN (SELECT HISM38,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
    SELECT HISM38, MAX(DESDES) as DESDES, SUM(HIS057) CANTIDAD, SUM(HISV22) VALOR
    FROM (SELECT HIS056, HISM38, HIS057, HISV22 FROM LBPRDDAT/hisa5804
    WHERE HISA60=".($anofiltro-1)." AND HISM37 BETWEEN 1 AND ".$mesfiltro." AND HIS056 IN (83,87)) T1
    INNER JOIN LBPRDDAT/DESARC T2 ON T1.HISM38=T2.DESCO1 AND T1.HIS056=T2.DESCOD
    GROUP BY HISM38))ANO2 ON ANO1.HISM38=ANO2.HISM38 WHERE ANO1.HISM38=".$marcaFiltro.") NIC ON HON.HISM38=NIC.HISM38";

$resultMarcas=odbc_exec($connIBM,$marcassql);


?>