<?php
function obtenerNombreMes($numeroMes) {
  $nombresMes = array('ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE');
  return $nombresMes[$numeroMes - 1];
}
function obtenerNombreMesAbr($numeroMes) {
  $nombresMes = array('Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic');
  return $nombresMes[$numeroMes - 1];
}
function obtenerNumeroMes($nombre_mes) {
  $nombres_mes = array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
  $numero_mes = array_search($nombre_mes, $nombres_mes) + 1;
  return $numero_mes;
}

 $mes_actual=date("m");
 $ano_actual=date("Y");
 $mesLabel1 = (isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes1'])):  obtenerNombreMesAbr(1);
 $mesLabel2 = (isset($_SESSION['mes2']) && $_SESSION['mes2']!=' ')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes2'])):  obtenerNombreMesAbr($mes_actual);
 $mesNum1=(isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNumeroMes($_SESSION['mes1']):  '01';
 $mesNum2=(isset($_SESSION['mes2']) && $_SESSION['mes2']!='')? obtenerNumeroMes($_SESSION['mes2']):  $mes_actual;

 $ano1 = (isset($_SESSION['ano1']) && $_SESSION['ano1']!='')? $_SESSION['ano1']:  $ano_actual;
 $ano2 = (isset($_SESSION['ano2']) && $_SESSION['ano2']!='')? $_SESSION['ano2']:  $ano_actual;
 $labelSelect= "$mesLabel1 $ano1 - $mesLabel2 $ano2";

      $mesfiltro=$mesNum2; 
      $anofiltro=isset($_SESSION['anofiltro'])? $_SESSION['anofiltro']: $ano_actual; 
      $marcaFiltro=isset($_SESSION['marcaFiltro'])? $_SESSION['marcaFiltro']: 100;
      if (strlen($mesfiltro)==1) {
        $mesfiltro="0".$mesfiltro;
      }
    //DESCRIPCIONES
    $marcasDescripcion="SELECT * FROM LBPRDDAT/DESARC WHERE DESCOD=01";
    $resultDescripcion=odbc_exec($connIBM,$marcasDescripcion);

    //VALORES
    $marcassql="SELECT HON.MARCA MARCA,HON.DESDES DESDES,HON.CANANO1 HONCANANO1,HON.VALANO1 HONVALANO1,HON.CANANO2 HONCANANO2,HON.VALANO2 HONVALANO2, 
                                                         GUA.CANANO1 GUACANANO1,GUA.VALANO1 GUAVALANO1,GUA.CANANO2 GUACANANO2,GUA.VALANO2 GUAVALANO2,
                                                         SAL.CANANO1 SALCANANO1,SAL.VALANO1 SALVALANO1,SAL.CANANO2 SALCANANO2,SAL.VALANO2 SALVALANO2,
                                                         COS.CANANO1 COSCANANO1,COS.VALANO1 COSVALANO1,COS.CANANO2 COSCANANO2,COS.VALANO2 COSVALANO2,
                                                         REP.CANANO1 REPCANANO1,REP.VALANO1 REPVALANO1,REP.CANANO2 REPCANANO2,REP.VALANO2 REPVALANO2,
                                                        NIC.CANANO1 NICCANANO1,NIC.VALANO1 NICVALANO1,NIC.CANANO2 NICCANANO2,NIC.VALANO2 NICVALANO2
FROM(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (35,47,50,52,56,57,59,63,64,65,68,70,72,73,74,75,76,78,82,85)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (35,47,50,52,56,57,59,63,64,65,68,70,72,73,74,75,76,78,82,85)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA WHERE ANO1.MARCA=".$marcaFiltro.") HON LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (49,66,69,71,86)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (49,66,69,71,86)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA WHERE ANO1.MARCA=".$marcaFiltro.")GUA ON HON.MARCA=GUA.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (48,53,61,62,77)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (48,53,61,62,77)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA WHERE ANO1.MARCA=".$marcaFiltro.")SAL ON HON.MARCA=SAL.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (54,60,80)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (54,60,80)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA WHERE ANO1.MARCA=".$marcaFiltro.")COS ON HON.MARCA=COS.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (83,87)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (83,87)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA WHERE ANO1.MARCA=".$marcaFiltro.")NIC ON HON.MARCA=NIC.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (81)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (81)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA WHERE ANO1.MARCA=".$marcaFiltro.")REP ON HON.MARCA=REP.MARCA";

$resultMarcas=odbc_exec($connIBM,$marcassql);


?>