<?php
    $_SESSION['FechaFiltro2'] = $_GET['dat'];
    $fecha=$_SESSION['FechaFiltro2'];
    $_SESSION['comppro2']=$_GET['id'];
        $anio =0;
        $mes =0;
        $dia =0;
    if ($fecha!="") {
        $anio = substr($fecha, 0, 4);
        $mes = substr($fecha, 4, 2);
        $dia = substr($fecha, 6, 2);
    }
    $fechaFiltro = implode("", array($dia, $mes, $anio));
    if ($_GET['dat']!="19700101" && $_GET['dat']!="") {
        $_SESSION['mesanterior']=$mes;
        $_SESSION['anioanterior']=$anio;
    }
    if($_GET['dat']=="19700101"){
        echo "<script>window.location = '/".$_SESSION['DEV']."LovablePHP/PRG/ZFA/ZLO0001PA.php?id=".$_SESSION['comppro2']."&dat='</script>";
    }
    $ckProductos1 = isset($_SESSION['productosCk1']) ? $_SESSION['productosCk1'] : "";
    $ckProductos2 = isset($_SESSION['productosCk2']) ? $_SESSION['productosCk2'] : "";
    
   
        if ($ckProductos1=="true") {
            if ($_GET['dat']!="") {
                //QUERY COMP 1 Y OTROS PRODUCTOS INCLUIDOS V2 QUITANDO NOTA DE CREDITO
            $sqlFacturaDia="SELECT FACCO4,FACNU3,FACAN1,(TM1.FACTO2 * TM1.FACFA3)-COALESCE((TM2.VALDES* TM1.FACFA3), 0) AS FACTO2,(TM1.FACSU3 * TM1.FACFA3)-COALESCE((TM2.VALBRU* TM1.FACFA3), 0) AS FACSU3,(TM1.FACIM1 * TM1.FACFA3)-COALESCE((TM2.VALIMP* TM1.FACFA3), 0) AS FACIM1,(TM1.FACTO3 * TM1.FACFA3)-COALESCE((TM2.VALNET* TM1.FACFA3), 0) AS FACTO3,FACFA3,FACFE1,FACTI3 FROM(
                SELECT FACCO4,FACNU3,FACAN1,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACFE1,FACTI3 FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,TOTFIN FACTO3,FACCAM FACFA3,FECFAC FACFE1,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
                FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACFE1,FACNU3,FACAN1,FACTI3 
                FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACCO4=".$_SESSION['comppro2']." AND FACFE1=".$fechaFiltro." AND FACAN1<>'A' AND T2.NUMFAC IS NULL) AS TM1 LEFT JOIN 
                LBPRDDAT/LO076804 AS TM2 ON TM1.FACNU3 = TM2.FACSIS AND TM1.FACCO4 = TM2.CODCIA";
            }else {
                $sqlFacturaDia="SELECT FACCO4,FACNU3,FACFE1,FACTI3,FACTO2,FACSU3,FACIM1,FACTO3 
                FROM (SELECT FACCO4,CASE WHEN FACCO4=1 AND FACTI3='USS' THEN 'LPS' ELSE FACTI3 END AS FACTI3,FACNU3,FACANO,FACME1,FACFE1,FACAN1,(TM1.FACTO2 * TM1.FACFA3)-COALESCE((TM2.VALDES* TM1.FACFA3), 0) AS FACTO2,(TM1.FACSU3 * TM1.FACFA3)-COALESCE((TM2.VALBRU* TM1.FACFA3), 0) AS FACSU3,
                (TM1.FACIM1 * TM1.FACFA3)-COALESCE((TM2.VALIMP* TM1.FACFA3), 0) AS FACIM1,(TM1.FACTO3 * TM1.FACFA3)-COALESCE((TM2.VALNET* TM1.FACFA3), 0) AS FACTO3,FACFA3 
                FROM(SELECT FACCO4,FACNU3,FACAN1,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACANO,FACME1,FACFE1,FACTI3 FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,
                TOTFIN FACTO3,FACCAM FACFA3,ANOPRO FACANO,MESPRO FACME1,FECFAC FACFE1,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
                FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACANO,FACME1,FACFE1,FACNU3,FACAN1,FACTI3 
                FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACCO4=".$_SESSION['comppro2']." AND FACME1=".$_SESSION['mesanterior']." AND FACANO=". $_SESSION['anioanterior']." AND FACAN1<>'A' AND T2.NUMFAC IS NULL) AS TM1 LEFT JOIN 
                LBPRDDAT/LO076804 AS TM2 ON TM1.FACNU3 = TM2.FACSIS AND TM1.FACCO4 = TM2.CODCIA )";
            }
            
                

        }else{
            if ($_GET['dat']!="") {
                //QUERY COMP 1 Y OTROS PRODUCTOS INCLUIDOS V2 QUITANDO NOTA DE CREDITO
                $sqlFacturaDia="SELECT FACCO4,FACNU3,FACTO2,FACFE1,FACSU3-VALTOTR FACSU3,(FACIM1 -(VALTOTR * (VALIMP/FACSU3))) FACIM1,CASE WHEN (FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)))<0 THEN 0 ELSE FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)) END FACTO3,FACTI3 FROM (
                    SELECT FACCO4,FACIM1,FACNU3,FACFE1,FACTO2,(FACSU3* FACFA3) FACSU3,COALESCE((VALCDE* FACFA3), 0) AS VALTOTR,(FACIM1* FACFA3) VALIMP, (FACTO3 * FACFA3) FACTO3,FACTI3 FROM(
                    SELECT * FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,TOTFIN FACTO3,FACCAM FACFA3, FECFAC FACFE1,ANOPRO FACANO,
                    MESPRO FACME1,NUMP10 FACP10,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
                    FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACFE1,FACANO,FACME1,FACP10,FACNU3,FACAN1,FACTI3 
                    FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACAN1<>'A') AS T3 LEFT JOIN (SELECT CODCIA,NUMFAC,SUM(VALCDE) VALCDE 
                    FROM(SELECT FACCO6 CODCIA,FACNU5 NUMFAC,FACMA1 MARCA,FACV02 VALCDE FROM LBPRDDAT/FACAR3
                    UNION ALL SELECT CODCIA,NUMFAC,MARCA,VALCDE FROM LBPRDDAT/LO043004) WHERE MARCA>=996 AND CODCIA=".$_SESSION['comppro2']." GROUP BY CODCIA,NUMFAC) AS T4 ON T4.NUMFAC=T3.FACNU3 
                    WHERE T3.NUMFAC IS NULL AND T3.FACCO4=".$_SESSION['comppro2']." AND T3.FACFE1=".$fechaFiltro.")";
            }else {
                $sqlFacturaDia="SELECT FACCO4,FACNU3,FACFE1,FACTI3, FACTO2,FACSU3,FACIM1,FACTO3 
            FROM (SELECT FACCO4,FACNU3,FACFE1,FACTO2,FACSU3-VALTOTR FACSU3,(FACIM1 -(VALTOTR * (VALIMP/FACSU3))) FACIM1,CASE WHEN (FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)))<0 THEN 0 ELSE FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)) END FACTO3,
            CASE WHEN FACCO4=1 AND FACTI3='USS' THEN 'LPS' ELSE FACTI3 END AS FACTI3 FROM (SELECT FACCO4,FACIM1,FACFE1,FACNU3,FACTO2,(FACSU3* FACFA3) FACSU3,COALESCE((VALCDE* FACFA3), 0) AS VALTOTR,(FACIM1* FACFA3) VALIMP, (FACTO3 * FACFA3) FACTO3,FACTI3 FROM(
            SELECT * FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,TOTFIN FACTO3,FACCAM FACFA3, FECFAC FACFE1,ANOPRO FACANO,
            MESPRO FACME1,NUMP10 FACP10,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
            FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACFE1,FACANO,FACME1,FACP10,FACNU3,FACAN1,FACTI3 
            FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACAN1<>'A') AS T3 LEFT JOIN (SELECT CODCIA,NUMFAC,SUM(VALCDE) VALCDE 
            FROM(SELECT FACCO6 CODCIA,FACNU5 NUMFAC,FACMA1 MARCA,FACV02 VALCDE FROM LBPRDDAT/FACAR3
            UNION ALL SELECT CODCIA,NUMFAC,MARCA,VALCDE FROM LBPRDDAT/LO043004) WHERE MARCA>=996 AND CODCIA=".$_SESSION['comppro2']." GROUP BY CODCIA,NUMFAC) AS T4 ON T4.NUMFAC=T3.FACNU3 
            WHERE T3.NUMFAC IS NULL AND T3.FACCO4=".$_SESSION['comppro2']." AND T3.FACME1=".$_SESSION['mesanterior']." AND T3.FACANO=". $_SESSION['anioanterior']."))";
            }
      
           
       }
        $resultFacturaDia=odbc_exec($connIBM,$sqlFacturaDia);

        if ($ckProductos2=="true") {
            if ($_GET['dat']!="") {
            $sqlFacturaMes="SELECT FACCO4,FACFE1,FACTI3,COUNT(*) AS FACTRA, SUM(FACTO2) FACTO2,SUM(FACSU3) FACSU3,SUM(FACIM1) FACIM1,SUM(FACTO3) FACTO3 
            FROM (SELECT FACCO4,CASE WHEN FACCO4=1 AND FACTI3='USS' THEN 'LPS' ELSE FACTI3 END AS FACTI3,FACNU3,FACANO,FACME1,FACFE1,FACAN1,(TM1.FACTO2 * TM1.FACFA3)-COALESCE((TM2.VALDES* TM1.FACFA3), 0) AS FACTO2,(TM1.FACSU3 * TM1.FACFA3)-COALESCE((TM2.VALBRU* TM1.FACFA3), 0) AS FACSU3,
            (TM1.FACIM1 * TM1.FACFA3)-COALESCE((TM2.VALIMP* TM1.FACFA3), 0) AS FACIM1,(TM1.FACTO3 * TM1.FACFA3)-COALESCE((TM2.VALNET* TM1.FACFA3), 0) AS FACTO3,FACFA3 
            FROM(SELECT FACCO4,FACNU3,FACAN1,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACANO,FACME1,FACFE1,FACTI3 FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,
            TOTFIN FACTO3,FACCAM FACFA3,ANOPRO FACANO,MESPRO FACME1,FECFAC FACFE1,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
            FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACANO,FACME1,FACFE1,FACNU3,FACAN1,FACTI3 
            FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACCO4=".$_SESSION['comppro2']." AND FACME1=".$mes." AND FACANO=".$anio." AND FACAN1<>'A' AND T2.NUMFAC IS NULL) AS TM1 LEFT JOIN 
            LBPRDDAT/LO076804 AS TM2 ON TM1.FACNU3 = TM2.FACSIS AND TM1.FACCO4 = TM2.CODCIA )GROUP BY FACCO4,FACFE1,FACTI3 ORDER BY FACFE1";
            }else {
                $sqlFacturaMes="SELECT FACCO4,FACFE1,FACTI3,COUNT(*) AS FACTRA, SUM(FACTO2) FACTO2,SUM(FACSU3) FACSU3,SUM(FACIM1) FACIM1,SUM(FACTO3) FACTO3 
                FROM (SELECT FACCO4,CASE WHEN FACCO4=1 AND FACTI3='USS' THEN 'LPS' ELSE FACTI3 END AS FACTI3,FACNU3,FACANO,FACME1,FACFE1,FACAN1,(TM1.FACTO2 * TM1.FACFA3)-COALESCE((TM2.VALDES* TM1.FACFA3), 0) AS FACTO2,(TM1.FACSU3 * TM1.FACFA3)-COALESCE((TM2.VALBRU* TM1.FACFA3), 0) AS FACSU3,
                (TM1.FACIM1 * TM1.FACFA3)-COALESCE((TM2.VALIMP* TM1.FACFA3), 0) AS FACIM1,(TM1.FACTO3 * TM1.FACFA3)-COALESCE((TM2.VALNET* TM1.FACFA3), 0) AS FACTO3,FACFA3 
                FROM(SELECT FACCO4,FACNU3,FACAN1,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACANO,FACME1,FACFE1,FACTI3 FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,
                TOTFIN FACTO3,FACCAM FACFA3,ANOPRO FACANO,MESPRO FACME1,FECFAC FACFE1,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
                FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACANO,FACME1,FACFE1,FACNU3,FACAN1,FACTI3 
                FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACCO4=".$_SESSION['comppro2']." AND FACME1=".$_SESSION['mesanterior']." AND FACANO=". $_SESSION['anioanterior']." AND FACAN1<>'A' AND T2.NUMFAC IS NULL) AS TM1 LEFT JOIN 
                LBPRDDAT/LO076804 AS TM2 ON TM1.FACNU3 = TM2.FACSIS AND TM1.FACCO4 = TM2.CODCIA )GROUP BY FACCO4,FACFE1,FACTI3 ORDER BY FACFE1";
            }
        }else {
            if ($_GET['dat']!="") {
            $sqlFacturaMes="SELECT FACCO4,FACFE1,FACTI3,COUNT(*) AS FACTRA, SUM(FACTO2) FACTO2,SUM(FACSU3) FACSU3,SUM(FACIM1) FACIM1,SUM(FACTO3) FACTO3 
            FROM (SELECT FACCO4,FACNU3,FACFE1,FACTO2,FACSU3-VALTOTR FACSU3,(FACIM1 -(VALTOTR * (VALIMP/FACSU3))) FACIM1,CASE WHEN (FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)))<0 THEN 0 ELSE FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)) END FACTO3,
            CASE WHEN FACCO4=1 AND FACTI3='USS' THEN 'LPS' ELSE FACTI3 END AS FACTI3 FROM (SELECT FACCO4,FACIM1,FACFE1,FACNU3,FACTO2,(FACSU3* FACFA3) FACSU3,COALESCE((VALCDE* FACFA3), 0) AS VALTOTR,(FACIM1* FACFA3) VALIMP, (FACTO3 * FACFA3) FACTO3,FACTI3 FROM(
            SELECT * FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,TOTFIN FACTO3,FACCAM FACFA3, FECFAC FACFE1,ANOPRO FACANO,
            MESPRO FACME1,NUMP10 FACP10,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
            FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACFE1,FACANO,FACME1,FACP10,FACNU3,FACAN1,FACTI3 
            FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACAN1<>'A') AS T3 LEFT JOIN (SELECT CODCIA,NUMFAC,SUM(VALCDE) VALCDE 
            FROM(SELECT FACCO6 CODCIA,FACNU5 NUMFAC,FACMA1 MARCA,FACV02 VALCDE FROM LBPRDDAT/FACAR3
            UNION ALL SELECT CODCIA,NUMFAC,MARCA,VALCDE FROM LBPRDDAT/LO043004) WHERE MARCA>=996 GROUP BY CODCIA,NUMFAC) AS T4 ON T4.NUMFAC=T3.FACNU3 
            WHERE T3.NUMFAC IS NULL AND T3.FACCO4=".$_SESSION['comppro2']." AND T3.FACME1=".$mes." AND T3.FACANO=".$anio."))GROUP BY FACCO4,FACFE1,FACTI3 ORDER BY FACFE1";
             }else {
            $sqlFacturaMes="SELECT FACCO4,FACFE1,FACTI3,COUNT(*) AS FACTRA, SUM(FACTO2) FACTO2,SUM(FACSU3) FACSU3,SUM(FACIM1) FACIM1,SUM(FACTO3) FACTO3 
                FROM (SELECT FACCO4,FACNU3,FACFE1,FACTO2,FACSU3-VALTOTR FACSU3,(FACIM1 -(VALTOTR * (VALIMP/FACSU3))) FACIM1,CASE WHEN (FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)))<0 THEN 0 ELSE FACTO3-VALTOTR-(VALTOTR * (VALIMP/FACSU3)) END FACTO3,
                CASE WHEN FACCO4=1 AND FACTI3='USS' THEN 'LPS' ELSE FACTI3 END AS FACTI3 FROM (SELECT FACCO4,FACIM1,FACFE1,FACNU3,FACTO2,(FACSU3* FACFA3) FACSU3,COALESCE((VALCDE* FACFA3), 0) AS VALTOTR,(FACIM1* FACFA3) VALIMP, (FACTO3 * FACFA3) FACTO3,FACTI3 FROM(
                SELECT * FROM(SELECT CODCIA FACCO4,TOTDES FACTO2, TOTCDE FACSU3, VALIMP FACIM1,TOTFIN FACTO3,FACCAM FACFA3, FECFAC FACFE1,ANOPRO FACANO,
                MESPRO FACME1,NUMP10 FACP10,NUMFAC FACNU3,ESTADO FACAN1,TIPFAC FACTI3 
                FROM LBPRDDAT/LO042902 UNION ALL SELECT FACCO4,FACTO2,FACSU3,FACIM1,FACTO3,FACFA3,FACFE1,FACANO,FACME1,FACP10,FACNU3,FACAN1,FACTI3 
                FROM LBPRDDAT/FACAR213)AS T1 LEFT JOIN LBPRDDAT/LO145101 AS T2 ON T1.FACNU3 = T2.NUMFAC WHERE FACAN1<>'A') AS T3 LEFT JOIN (SELECT CODCIA,NUMFAC,SUM(VALCDE) VALCDE 
                FROM(SELECT FACCO6 CODCIA,FACNU5 NUMFAC,FACMA1 MARCA,FACV02 VALCDE FROM LBPRDDAT/FACAR3
                UNION ALL SELECT CODCIA,NUMFAC,MARCA,VALCDE FROM LBPRDDAT/LO043004) WHERE MARCA>=996 GROUP BY CODCIA,NUMFAC) AS T4 ON T4.NUMFAC=T3.FACNU3 
                WHERE T3.NUMFAC IS NULL AND T3.FACCO4=".$_SESSION['comppro2']." AND T3.FACME1=".$_SESSION['mesanterior']." AND T3.FACANO=". $_SESSION['anioanterior']."))GROUP BY FACCO4,FACFE1,FACTI3 ORDER BY FACFE1";
             }
        }
        $resultFacturaMes=odbc_exec($connIBM,$sqlFacturaMes);
  //COMBOBOX
  $sqlCOMARC = "SELECT T2.CODSEC,LO0705.CODCIA COMCOD, LO0705.NOMCIA COMDES 
  FROM LBPRDDAT/LO0705
  INNER JOIN LBPRDDAT/DETA16 ON DETA16.DETC90 = LO0705.CODCIA
  INNER JOIN LBPRDDAT/LO0686 AS T2 ON T2.CODCIA = LO0705.CODCIA
  WHERE DETA16.DETUSU ='".$_SESSION["CODUSU"]."' AND DETA16.DETPR1 = 'LO1512P' 
  ORDER BY T2.CODSEC";
  $resultCOMARC=odbc_exec($connIBM,$sqlCOMARC);
  $resultCOMARC2=odbc_exec($connIBM,$sqlCOMARC);

  function obtenerNombreDia($fecha) {
    $dias_semana = array("Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado");
    $indice_dia = date('w', strtotime($fecha));
    return $dias_semana[$indice_dia];
  }


?>