<?php
function obtenerNombreMes($numeroMes) {
    $nombresMes = array('ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', 'DICIEMBRE');
    return $nombresMes[$numeroMes - 1];
  }
  function obtenerNombreMesAbr($numeroMes) {
    $nombresMes = array('Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic');
    return $nombresMes[$numeroMes - 1];
  }
  function obtenerNumeroMes($nombre_mes) {
    $nombres_mes = array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
    $numero_mes = array_search($nombre_mes, $nombres_mes) + 1;
    return $numero_mes;
  }
  
   $mes_actual=date("m");
   $ano_actual=date("Y");
   $mesLabel1 = (isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes1'])):  obtenerNombreMesAbr(1);
   $mesLabel2 = (isset($_SESSION['mes2']) && $_SESSION['mes2']!=' ')? obtenerNombreMesAbr(obtenerNumeroMes($_SESSION['mes2'])):  obtenerNombreMesAbr($mes_actual);
   $mesNum1=(isset($_SESSION['mes1']) && $_SESSION['mes1']!='')? obtenerNumeroMes($_SESSION['mes1']):  '01';
   $mesNum2=(isset($_SESSION['mes2']) && $_SESSION['mes2']!='')? obtenerNumeroMes($_SESSION['mes2']):  $mes_actual;
  
   $ano1 = (isset($_SESSION['ano1']) && $_SESSION['ano1']!='')? $_SESSION['ano1']:  $ano_actual;
   $ano2 = (isset($_SESSION['ano2']) && $_SESSION['ano2']!='')? $_SESSION['ano2']:  $ano_actual;
   $labelSelect= "$mesLabel1 $ano1 - $mesLabel2 $ano2";
  
        $mesfiltro=$mesNum2; 
        $anofiltro=isset($_SESSION['anofiltro'])? $_SESSION['anofiltro']: $ano_actual; 
        $marcaFiltro=isset($_SESSION['marcaFiltro'])? $_SESSION['marcaFiltro']: 100;
        if (strlen($mesfiltro)==1) {
          $mesfiltro="0".$mesfiltro;
        }
//DESCRIPCIONES
$marcasDescripcion="SELECT * FROM LBPRDDAT/DESARC WHERE DESCOD=01";
$resultDescripcion=odbc_exec($connIBM,$marcasDescripcion);
$_SESSION['mesFiltro']=$_SESSION['mesFiltro']-1;
$valorFiltro=$anofiltro.(strlen($_SESSION['mesFiltro'])==1? "0".$_SESSION['mesFiltro']:$_SESSION['mesFiltro']);

//HONDURAS
 $marcassql="SELECT HON.MARCA MARCA,HON.DESDES DESDES,HON.CANANO1 CANHON,HON.VALANO1 VALHON,HON.CANANO2 CANHON2,HON.VALANO2 VALHON2, 
                                                        GUA.CANANO1 CANGUA,GUA.VALANO1 VALGUA,GUA.CANANO2 CANGUA2,GUA.VALANO2 VALGUA2,
                                                        SAL.CANANO1 CANSAL,SAL.VALANO1 VALSAL,SAL.CANANO2 CANSAL2,SAL.VALANO2 VALSAL2,
                                                        COS.CANANO1 CANCOS,COS.VALANO1 VALCOS,COS.CANANO2 CANCOS2,COS.VALANO2 VALCOS2,
                                                        REP.CANANO1 CANREP,REP.VALANO1 VALREP,REP.CANANO2 CANREP2,REP.VALANO2 VALREP2,
                                                        NIC.CANANO1 CANNIC,NIC.VALANO1 VALNIC,NIC.CANANO2 CANNIC2,NIC.VALANO2 VALNIC2
FROM(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (35,47,50,52,56,57,59,63,64,65,68,70,72,73,74,75,76,78,82,85)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (35,47,50,52,56,57,59,63,64,65,68,70,72,73,74,75,76,78,82,85)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA) HON LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (49,66,69,71,86)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (49,66,69,71,86)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA )GUA ON HON.MARCA=GUA.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (48,53,61,62,77)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (48,53,61,62,77)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA )SAL ON HON.MARCA=SAL.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (54,60,80)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (54,60,80)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA )COS ON HON.MARCA=COS.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (83,87)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (83,87)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA )NIC ON HON.MARCA=NIC.MARCA LEFT JOIN
(SELECT ANO1.MARCA MARCA,ANO1.DESDES,ANO1.CANTIDAD CANANO1,ANO1.VALOR VALANO1, ANO2.CANTIDAD CANANO2,ANO2.VALOR  VALANO2
FROM (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD, VALOR FROM (
SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (81)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO1 INNER JOIN (SELECT MARCA,DESDES,FLOOR(((FLOOR(CANTIDAD)*12) +ROUND((CANTIDAD - FLOOR(CANTIDAD)) * 100))) CANTIDAD,
VALOR FROM (SELECT MARCA, MAX(DESDES) as DESDES, SUM(CANVEN) CANTIDAD, SUM(VALVEN) VALOR
FROM (SELECT CODCIA, MARCA, CANVEN, VALVEN FROM LBPRDDAT/lo2234
WHERE ANOPRO=".($ano2-1)." AND MESPRO BETWEEN ".$mesNum1." AND ".$mesNum2." AND CODCIA IN (81)) T1
INNER JOIN LBPRDDAT/DESARC T2 ON T1.MARCA=T2.DESCO1 AND T1.CODCIA=T2.DESCOD
GROUP BY MARCA))ANO2 ON ANO1.MARCA=ANO2.MARCA )REP ON HON.MARCA=REP.MARCA";

    $resultMarcas=odbc_exec($connIBM,$marcassql);
  


?>